# Generated by Django 4.0.1 on 2022-02-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klimatologi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tn', models.FloatField(blank=True)),
                ('tx', models.FloatField(blank=True)),
                ('tavg', models.FloatField(blank=True)),
                ('rh_avg', models.FloatField(blank=True)),
                ('rr', models.FloatField(blank=True)),
                ('ss', models.FloatField(blank=True)),
                ('ff_x', models.FloatField(blank=True)),
                ('ddd_x', models.FloatField(blank=True)),
                ('ff_avg', models.FloatField(blank=True)),
                ('ddd_car', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
